# Generated by Django 5.0.1 on 2024-01-02 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intrests',
            fields=[
                ('intrests_id', models.AutoField(primary_key=True, serialize=False)),
                ('intrests_name', models.CharField(max_length=255, unique=True)),
                ('intrests_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingParadigm',
            fields=[
                ('paradigm_id', models.AutoField(primary_key=True, serialize=False)),
                ('paradigm_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_joined', models.IntegerField()),
                ('year_Ended', models.IntegerField()),
                ('grade_attained', models.CharField(max_length=55)),
                ('certificate_earned', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255)),
                ('percentage_coverage', models.IntegerField()),
                ('programming_paradigm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.programmingparadigm')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsbilities', models.TextField()),
                ('achievements', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.company')),
            ],
        ),
    ]
