# Generated by Django 5.0.1 on 2024-01-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_Ended',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_joined',
            field=models.CharField(max_length=12),
        ),
    ]
