# Generated by Django 5.0.1 on 2024-01-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_year_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year_Ended',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_joined',
            field=models.IntegerField(),
        ),
    ]
