# Generated by Django 5.0.1 on 2024-01-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_education_year_ended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='company',
            new_name='company_name',
        ),
    ]
