# Generated by Django 5.0.1 on 2024-01-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_workexperience_responsbilities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
