# Generated by Django 5.0.1 on 2024-01-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
