# Generated by Django 5.0.1 on 2024-01-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_delete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mydesc',
            field=models.CharField(max_length=900),
        ),
    ]
