# Generated by Django 5.0.1 on 2024-01-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_alter_about_mydesc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
